# -*- coding: utf-8 -*-
{
    'name': 'Agenda',
    'version': '1.0',
    'depends': ['base'],
    'summary': 'Agenda Electronica Academica',
    'author': 'Diego Vargas',
    'category': 'Education',
    'description': 'Módulo de agenda escolar con alumnos, tutores, cursos, materias y profesores.',
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        # 'data/data.xml',
        'views/tutor_views.xml',
        'views/alumno_views.xml',
        'views/curso_views.xml',
        'views/gestion_views.xml',
        'views/materia_views.xml',
        'views/profesor_views.xml',
        'views/administrativo_views.xml',
        'views/notificacion_views.xml',
        'views/inscripcion_views.xml',
        'views/asignacion_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
